collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.nxos
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: community.postgresql
  - name: community.vmware
  - name: community.windows
  - name: community.zabbix
  - name: microsoft.ad
  - name: microsoft.iis
  - name: netapp.ontap
  - name: vmware.vmware
